### PR TITLE
Improve Node UX

### PR DESCRIPTION
**Pull request by LLParse**
https://github.com/rancher/longhorn/issues/306

### CODE REVIEW

**Comment by LLParse** [comment]
@yasker Ready for review

**Comment by yasker** [comment]
Either don't show `Remove Node` when it's not possible to remove or add a tooltip say something like `The node must be removed from Kubernetes first` when users hover over the action. Otherwise, users would be confused about why this action is not available.

**Comment by LLParse** [comment]
@yasker Ready for review

**Comment by yasker** [comment]
The `delete` option in the dropdown for a replica in volume attaching/detaching state should also be disabled. And we can add a tooltip there as well.

Other than that, LGTM.

**Comment by LLParse** [comment]
@yasker

**Pull request merged**
